
# Code generated by codegen


def cmd_btn1():
    print('Meine Seite gedrückt')

def beenden():
    print('Ende gedrückt')

def starten():
    print('Button 3 gedrückt')

def aktivieren():
    print('Button 5 gedrückt')

def drucke():
    print('Button 7 gedrückt')

def func8():
    print('Button 8 gedrückt')
